### PR TITLE
Map plotting

### PR DESCRIPTION
**Pull request by ArktinenSieni**
WIP. Plz don't merge <3

### CODE REVIEW

**Comment by ArktinenSieni** [comment]
Issue #35

**Comment by ArktinenSieni** [comment]
Done. Now yellow circles represent sum of averages in the measurement-points.

**Comment by ArktinenSieni** [comment]
Images (excluding the initial measurement-point-png) were created with pyplot's UI.

**Comment by mikhuttu** [comment]
Looks really nice. Great job! :)

**Pull request merged**
